PATH :
  INPUT : "path_to_input_files/"
  OUTPUT : "path_to_output_folder/"

NUM : ['0','1','2','3','4','5','6','7','8','9'] # Random seed numbers

DB : ['hippie', 'intact', 'biogrid'] # PPI network databases

PARAMS: ["k0.1_ep50_plmpool1_d1_l3_po8_lr0.001"] # Hyperparameters for the model